apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
      version: green
  template:
    metadata:
      labels:
        app: demoapp
        version: green
    spec:
      containers:
        - name: demoapp
          image: dockerimage
          ports:
            - containerPort: 8080